name: Review

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello, ${{ github.actor }}, Thanks you for opening an issue. Soon the maintainers/owers will review it and provide you with feedback/suggestions. If you think its something urgent, feel free to reach on social handles.'
          pr-message: 'Hello, ${{ github.actor }}, Thanks you for raising a PR. Soon the maintainers/owers will review it and provide you with feedback/suggestions. If you think its something urgent, feel free to reach on social handles.'
